/* Generated By:JJTree&JavaCC: Do not edit this line. TestParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TestParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPAR = 1;
  /** RegularExpression Id. */
  int CPAR = 2;
  /** RegularExpression Id. */
  int OBR = 3;
  /** RegularExpression Id. */
  int CBR = 4;
  /** RegularExpression Id. */
  int COL = 5;
  /** RegularExpression Id. */
  int SCOL = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int CONST = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int ALPHANUM = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"var\"",
    "\"=\"",
    "\"const\"",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUM>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
  };

}
