/* Generated By:JavaCC: Do not edit this line. TestParserTreeConstants.java Version 5.0 */
public interface TestParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECL = 1;
  public int JJTVAR = 2;
  public int JJTCONST = 3;
  public int JJTFUNCTION = 4;
  public int JJTTYPE = 5;
  public int JJTID = 6;
  public int JJTPARAMS = 7;
  public int JJTPARAM = 8;
  public int JJTEXPR = 9;


  public String[] jjtNodeName = {
    "PROGRAM",
    "decl",
    "VAR",
    "CONST",
    "FUNCTION",
    "TYPE",
    "ID",
    "PARAMS",
    "PARAM",
    "EXPR",
  };
}
/* JavaCC - OriginalChecksum=6910ce5a32ead5e39611a25558496390 (do not edit this line) */
