// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {NodeProp} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "!WQYQPOOOhQPO'#CdOOQO'#Ci'#CiOOQO'#Ce'#CeQYQPOOOOQO,59O,59OOyQPO,59OOOQO-E6c-E6cOOQO1G.j1G.j",
  stateData: "![~O[OSPOS~ORQOSQOTQOVPO~ORQOSQOTQOUTOVPO~ORQOSQOTQOUWOVPO~O",
  goto: "u^PPPPPPPP_ePPPoXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ LineComment Program Identifier String Boolean ) ( Application",
  maxTerm: 13,
  nodeProps: [
    [NodeProp.openedBy, 6,"("],
    [NodeProp.closedBy, 7,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "#z~R[XYwYZw]^wpqwrs!Yst!wxy#Vyz#[!]!^#a!c!}#l#R#S#l#T#o#l~|S[~XYwYZw]^wpqw~!]TOr!Yrs!ls#O!Y#O#P!q#P~!Y~!qOS~~!tPO~!Y~!zQ#Y#Z#Q#h#i#Q~#VOT~~#[OV~~#aOU~~#fQP~OY#aZ~#a~#qRR~!c!}#l#R#S#l#T#o#l",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
